### ISSUE TITLE
XGBoost 0.4.1 build failing on linux (but not mac) in MLJ travis build

### ISSUE THREAD

**Issue by ablaom** [dmlc/XGBoost.jl#69]
Not been able to reproduce this locally.

Travis fail is for Julia 1 and 1.1 and nightly for linux only

https://travis-ci.com/alan-turing-institute/MLJModels.jl/jobs/210361097

<img width="1005" alt="Screen Shot 2019-06-24 at 3 06 09 PM" src="https://user-images.githubusercontent.com/30517088/60025591-e224d600-9691-11e9-84a5-dab34dbea872.png">

**Comment by aviks** [comment]
I tried on a local linux machine, and it worked fine. XGBoost's own Travis tests seem to work fine. 

Do you have any OS version specifiers in your travis jobs? 

paging @staticfloat -- help!

**Comment by ablaom** [comment]
I'm not sure I understand the question. We run tests for Mac and Linux:

```
## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'

## uncomment following lines to deploy documentation
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      # disable global before_script in order not to install Compose twice
      before_script:
      script:
        - |
          julia --color=yes --project=docs/ -e'
            using Pkg
            Pkg.add(PackageSpec(name="MLJBase", rev="master"));Pkg.add(PackageSpec(name="MLJModels", rev="master"));Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")
          '
```
